export const KEYBOARD_VIEWS = {
  BASIC: 'BasicMathKeyboard',
  LOWERCASE: 'LowercaseKeyboard',
  UPPERCASE: 'UppercaseKeyboard',
  LETTER_LIKE_SYMBOLS: 'LetterLikeSymbolsKeyboard',
  COMMON_BINARY_OPERATORS: 'CommonBinaryOperatorsKeyboard',
  COMMON_RELATIONAL_OPERATORS: 'CommonRelationalOperatorsKeyboard',
  BASIC_NARY_OPERATORS: 'BasicNaryOperatorsKeyboard',
  ADVANCED_BINARY_OPERATORS: 'AdvancedBinaryOperatorsKeyboard',
  ADVANCED_RELATIONAL_OPERATORS: 'AdvancedRelationalOperatorsKeyboard',
  ARROWS: 'ArrowsKeyboard',
  NEGATED_RELATIONS: 'NegatedRelationsKeyboard',
  SCRIPTS: 'ScriptsKeyboard',
  FRAKTURS: 'FraktursKeyboard',
  DOUBLE_STRUCK: 'DoubleStruckKeyboard',
  GEOMETRY: 'GeometryKeyboard',
  COMMON_MATH: 'CommonMathKeyboard',
};
