import MathView, { MathjaxFactory } from 'react-native-math-view';


export const basicMath = [
  '\\pm',
  '\\infty',
  '=',
  '\\neq',
  '\\sim', // '~',
  '\\times',
  '\\div',
  '!',
  '\\propto',
  '<',
  '\\ll',
  '>',
  '\\gg',
  '\\le',
  '\\geq',
  '\\mp',
  '\\cong',
  '\\approx',
  '\\equiv',
  '\\forall',
  '\\complement',
  '\\partial',
  '\\sqrt{}', // '\\sqrt',
  '\\sqrt[3]{}', // '\\cbrt',
  '\\sqrt[4]{}', // '\\qdrt',
  '\\cup',
  '\\cap',
  '\\emptyset',
  '\\%',
  '^\\circ', // '\\degree',
  '^\\circ{C}', // '\\degf',
  '^\\circ{F}', // '\\degc',
  '\\Delta', // '\\inc',
  '\\nabla',
  '\\exists',
  // '\\nexists',
  '\\in',
  '\\ni',
  '\\gets',
  '\\uparrow',
  '\\rightarrow',
  '\\downarrow',
  '\\leftrightarrow',
  '\\therefore',
  '+',
  '-',
  '\\lnot',
  '\\alpha',
  '\\beta',
  '\\gamma',
  '\\delta',
  '\\varepsilon',
  '\\epsilon',
  '\\theta',
  '\\vartheta',
  '\\mu',
  '\\pi',
  '\\rho',
  '\\sigma',
  '\\tau',
  '\\varphi',
  '\\omega',
  '\\ast',
  '\\bullet',
  '\\vdots',
  '\\cdots',
  // '\\rddots',
  '\\ddots',
  '\\aleph',
  '\\beth',
  '\\blacksquare', // '\\qed',
];

export const lowercase = [
  '\\alpha',
  '\\beta',
  '\\gamma',
  '\\delta',
  '\\varepsilon',
  '\\epsilon',
  '\\zeta',
  '\\eta',
  '\\theta',
  '\\vartheta',
  '\\iota',
  '\\kappa',
  '\\lambda',
  '\\mu',
  '\\nu',
  '\\xi',
  '\\omicron', // '\\ο',
  '\\pi',
  '\\varpi',
  '\\rho',
  '\\varrho',
  '\\sigma',
  '\\varsigma',
  '\\tau',
  '\\upsilon',
  '\\varphi',
  '\\phi',
  '\\chi',
  '\\psi',
  '\\omega',
];

export const uppercase = [
  'Α',
  'Β',
  '\\Gamma',
  '\\Delta',
  'Ε',
  'Ζ',
  'Η',
  '\\Theta',
  'Ι',
  'Κ',
  '\\Lambda',
  'Μ',
  'Ν',
  '\\Xi',
  'Ο',
  '\\Pi',
  'Ρ',
  '\\Sigma',
  'Τ',
  '\\Upsilon',
  '\\Phi',
  'Χ',
  '\\Psi',
  '\\Omega',
];

export const letterLikeSymbols = [
  '\\forall',
  '\\complement',
  '\\mathbb{C}',
  '\\partial',
  'ð',
  // 'ℇ',
  // 'Ϝ',
  // 'Ⅎ',
  '\\mathcal{g}',
  '\\mathcal{H}',
  '\\mathfrak{H}',
  'h',
  '\\hbar',
  // '℩',
  '\\imath',
  '\\mathfrak{I}',
  'j',
  '\\varkappa',
  '\\mathcal{L}',
  '\\ell',
  '\\mathbb{N}',
  '\\wp',
  '\\mathbb{Q}',
  '\\mathcal{R}',
  '\\mathfrak{R}',
  '\\mathbb{R}',
  '\\mathbb{Z}',
  '℧',
  // 'Å',
  '\\mathcal{B}',
  // '℮',
  '\\mathcal{E}',
  '\\exists',
  // '\\nexists',
  '\\mathcal{F}',
  '\\mathcal{M}',
  '\\mathcal{o}',
  '\\aleph',
  '\\beth',
  '\\gimel',
  '\\daleth',
];

export const commonBinaryOperators = [
  '+',
  '-',
  '\\div',
  '\\times',
  '\\pm',
  '\\mp',
  '\\propto',
  '/',
  '\\ast',
  '\\circ',
  '\\bullet',
  '\\cdot',
  '\\cap',
  '\\cup',
  '\\uplus',
  '\\sqcap',
  '\\sqcup',
  '\\land',
  '\\vee',
];

export const commonRelationalOperators = [
  '=',
  '\\neq',
  '<',
  '>',
  '\\le',
  '\\geq',
  '\\nless',
  '\\nleq',
  '\\not\\gt', // '\\ngt',
  '\\ngeq',
  '\\equiv',
  '\\sim',
  '\\simeq',
  '\\approx',
  '\\cong',
  // '\\not\\equiv', // '\\nequiv',
  // '\\not\\simeq', // '\\nsimeq',
  // '\\not\\approx', // '\\napprox',
  // '\\ncong',
  '\\propto',
  '\\ll',
  '\\gg',
  '\\in',
  '\\ni',
  '\\notin',
  '\\subset',
  '\\supset',
  '\\subseteq',
  '\\supseteq',
  // '\\prcue',
  '\\succ',
  '\\preccurlyeq',
  '\\succcurlyeq',
  '\\sqsubset',
  '\\sqsupset',
  '\\sqsubseteq',
  '\\sqsupseteq',
  '\\parallel',
  '\\bot',
  '\\vdash',
  '\\dashv',
  '\\bowtie',
  '\\asymp',
];

export const basicNaryOperators = [
  '\\sum',
  '\\int',
  '\\iint',
  '\\iiint',
  '\\oint',
  // '\\oiint',
  // '\\oiiint',
  // '\\cwint',
  // '\\coint',
  // '\\aoint',
  '\\prod',
  '\\amalg',
  '\\bigcap',
  '\\bigcup',
  '\\bigwedge',
  '\\bigvee',
  '\\bigodot',
  '\\bigotimes',
  '\\bigoplus',
  '\\biguplus',
  // '\\bigudot',
];

export const advancedBinaryOperators = [
  '\\dotplus',
  // '\\dotminus',
  '\\setminus',
  '\\Cap',
  '\\Cup',
  '\\boxminus',
  '\\boxtimes',
  '\\boxdot',
  '\\boxplus',
  '\\divideontimes',
  '\\ltimes',
  '\\rtimes',
  '\\leftthreetimes',
  '\\rightthreetimes',
  '\\curlywedge',
  '\\curlyvee',
  // '\\odash',
  '\\intercal',
  '\\oplus',
  '\\ominus',
  '\\otimes',
  '\\oslash',
  '\\odot',
  // '\\oast',
  // '\\ocirc',
  // '\\dag',
  // '\\ddag',
  '\\star',
  '\\diamond',
  '\\wr',
  '\\triangle',
  '\\bigwedge',
  '\\bigvee',
  '\\bigodot',
  '\\bigotimes',
  '\\bigoplus',
  // '\\bigsqcap',
  '\\bigsqcup',
  '\\biguplus',
  // '\\bigudot',
];

export const advancedRelationalOperators = [
  '\\therefore',
  '\\because',
  '\\lll',
  '\\ggg',
  '\\leqq',
  '\\geqq',
  '\\lesssim',
  '\\gtrsim',
  '\\lessdot',
  '\\gtrdot',
  '\\lessgtr',
  '\\lesseqgtr',
  '\\gtrless',
  '\\gtreqless',
  '\\Doteq',
  '\\fallingdotseq',
  '\\risingdotseq',
  '\\backsim',
  '\\approxeq',
  '\\backsimeq',
  '\\preccurlyeq',
  '\\succcurlyeq',
  '\\curlyeqprec',
  '\\curlyeqsucc',
  '\\precsim',
  '\\succsim',
  // '\\eqless',
  // '\\eqgtr',
  '\\subseteq',
  '\\supseteq',
  '\\vartriangleleft',
  '\\vartriangleright',
  '\\trianglelefteq',
  '\\trianglerighteq',
  '\\models',
  '\\Subset',
  '\\Supset',
  '\\sqsubset',
  '\\sqsupset',
  '\\Vdash',
  '\\Vvdash',
  '\\eqcirc',
  '\\circeq',
  // '\\Deltaeq',
  '\\bumpeq',
  '\\Bumpeq',
  '\\propto',
  '\\between',
  '\\pitchfork',
  '\\doteq',
  '\\bowtie',
];

export const arrows = [
  '\\gets',
  '\\rightarrow',
  '\\uparrow',
  '\\downarrow',
  '\\leftrightarrow',
  '\\updownarrow',
  '\\Leftarrow',
  '\\Rightarrow',
  '\\Uparrow',
  '\\Downarrow',
  '\\Leftrightarrow',
  '\\Updownarrow',
  '\\longleftarrow',
  '\\longrightarrow',
  '\\longleftrightarrow',
  '\\Longleftarrow',
  '\\Longrightarrow',
  '\\Longleftrightarrow',
  '\\nearrow',
  '\\nwarrow',
  '\\searrow',
  '\\swarrow',
  '\\nleftarrow',
  '\\nrightarrow',
  '\\nleftrightarrow',
  '\\nLeftarrow',
  '\\nRightarrow',
  '\\nLeftrightarrow',
  '\\dashleftarrow',
  '\\dashrightarrow',
  // '\\mapstoleft',
  '\\mapsto',
  // '\\longmapstoleft',
  '\\longmapsto',
  '\\hookleftarrow',
  '\\hookrightarrow',
  '\\leftharpoonup',
  '\\leftharpoondown',
  '\\rightharpoonup',
  '\\rightharpoondown',
  '\\upharpoonleft',
  '\\upharpoonright',
  '\\downharpoonleft',
  '\\downharpoonright',
  '\\leftrightharpoons',
  // '\\rlhar',
  '\\leftleftarrows',
  '\\rightrightarrows',
  '\\upuparrows',
  '\\downdownarrows',
  '\\leftrightarrows',
  '\\rightleftarrows',
  '\\looparrowleft',
  '\\looparrowright',
  '\\leftarrowtail',
  '\\rightarrowtail',
  '\\Lsh',
  '\\Rsh',
  // '\\ldsh',
  // '\\rdsh',
  '\\Lleftarrow',
  '\\Rrightarrow',
  '\\twoheadleftarrow',
  '\\twoheadrightarrow',
  '\\curvearrowleft',
  '\\curvearrowright',
  '\\circlearrowleft',
  '\\circlearrowright',
  '\\multimap',
  // '\\leftrightwavearrow',
  // '\\leftwavearrow',
  // '\\rightwavearrow',
  // '\\leftsquigarrow',
  '⇝',
];

export const negatedRelations = [
  '\\neq',
  '\\nless',
  '\\not\\gt', // '\\ngt',
  '\\nleq',
  '\\ngeq',
  // '\\not\\equiv', // '\\nequiv',
  '\\nsim',
  // '\\not\\simeq', // '\\nsimeq',
  // '\\not\\approx', // '\\napprox',
  // '\\ncong',
  // '\\not\\asymp', // '\\nasymp',
  '\\lneqq',
  '\\gneqq',
  '\\nprec',
  '\\nsucc',
  '\\not\\preccurlyeq', // '\\npreccurlyeq',
  '\\not\\succcurlyeq', // '\\nsucccurlyeq',
  '\\notin',
  // '\\not\\ni', // '\\notni',
  // '\\nsub',
  // '\\nsup',
  '\\nsubseteq',
  '\\nsupseteq',
  '⊊',
  '\\supsetneq',
  // '\\not\\sqsubseteq', // '\\nsqsubseteq',
  // '\\not\\sqsupseteq', // '\\nsqsupseteq',
  '\\lnsim',
  '\\gnsim',
  '\\precnsim',
  '\\succnsim',
  '\\ntriangleleft',
  '\\ntriangleright',
  '\\ntrianglelefteq',
  '\\ntrianglerighteq',
  '\\nmid',
  '\\nparallel',
  '\\nvdash',
  '\\nvDash',
  '\\nVdash',
  '\\nVDash',
  // '\\nexists',
];

export const scripts = [
  '\\mathcal{A}',
  '\\mathcal{B}',
  '\\mathcal{C}',
  '\\mathcal{D}',
  '\\mathcal{E}',
  '\\mathcal{F}',
  '\\mathcal{G}',
  '\\mathcal{H}',
  '\\mathcal{I}',
  '\\mathcal{J}',
  '\\mathcal{K}',
  '\\mathcal{L}',
  '\\mathcal{M}',
  '\\mathcal{N}',
  '\\mathcal{O}',
  '\\mathcal{P}',
  '\\mathcal{Q}',
  '\\mathcal{R}',
  '\\mathcal{S}',
  '\\mathcal{T}',
  '\\mathcal{U}',
  '\\mathcal{V}',
  '\\mathcal{W}',
  '\\mathcal{X}',
  '\\mathcal{Y}',
  '\\mathcal{Z}',
  '\\mathcal{a}',
  '\\mathcal{b}',
  '\\mathcal{c}',
  '\\mathcal{d}',
  '\\mathcal{e}',
  '\\mathcal{f}',
  '\\mathcal{g}',
  '\\mathcal{h}',
  '\\mathcal{i}',
  '\\mathcal{j}',
  '\\mathcal{k}',
  '\\ell',
  '\\mathcal{m}',
  '\\mathcal{n}',
  '\\mathcal{o}',
  '\\mathcal{p}',
  '\\mathcal{q}',
  '\\mathcal{r}',
  '\\mathcal{s}',
  '\\mathcal{t}',
  '\\mathcal{u}',
  '\\mathcal{v}',
  '\\mathcal{w}',
  '\\mathcal{x}',
  '\\mathcal{y}',
  '\\mathcal{z}',
];

export const frakturs = [
  '\\mathfrak{A}',
  '\\mathfrak{B}',
  '\\mathfrak{C}',
  '\\mathfrak{D}',
  '\\mathfrak{E}',
  '\\mathfrak{F}',
  '\\mathfrak{G}',
  '\\mathfrak{H}',
  '\\mathfrak{I}',
  '\\mathfrak{J}',
  '\\mathfrak{K}',
  '\\mathfrak{L}',
  '\\mathfrak{M}',
  '\\mathfrak{N}',
  '\\mathfrak{O}',
  '\\mathfrak{P}',
  '\\mathfrak{Q}',
  '\\mathfrak{R}',
  '\\mathfrak{S}',
  '\\mathfrak{T}',
  '\\mathfrak{U}',
  '\\mathfrak{V}',
  '\\mathfrak{W}',
  '\\mathfrak{X}',
  '\\mathfrak{Y}',
  '\\mathfrak{Z}',
  '\\mathfrak{a}',
  '\\mathfrak{b}',
  '\\mathfrak{c}',
  '\\mathfrak{d}',
  '\\mathfrak{e}',
  '\\mathfrak{f}',
  '\\mathfrak{g}',
  '\\mathfrak{h}',
  '\\mathfrak{i}',
  '\\mathfrak{j}',
  '\\mathfrak{k}',
  '\\mathfrak{l}',
  '\\mathfrak{m}',
  '\\mathfrak{n}',
  '\\mathfrak{o}',
  '\\mathfrak{p}',
  '\\mathfrak{q}',
  '\\mathfrak{r}',
  '\\mathfrak{s}',
  '\\mathfrak{t}',
  '\\mathfrak{u}',
  '\\mathfrak{v}',
  '\\mathfrak{w}',
  '\\mathfrak{x}',
  '\\mathfrak{y}',
  '\\mathfrak{z}',
];

export const doubleStruck = [
  '\\mathbb{A}',
  '\\mathbb{B}',
  '\\mathbb{C}',
  '\\mathbb{D}',
  '\\mathbb{E}',
  '\\mathbb{F}',
  '\\mathbb{G}',
  '\\mathbb{H}',
  '\\mathbb{I}',
  '\\mathbb{J}',
  '\\mathbb{K}',
  '\\mathbb{L}',
  '\\mathbb{M}',
  '\\mathbb{N}',
  '\\mathbb{O}',
  '\\mathbb{P}',
  '\\mathbb{Q}',
  '\\mathbb{R}',
  '\\mathbb{S}',
  '\\mathbb{T}',
  '\\mathbb{U}',
  '\\mathbb{V}',
  '\\mathbb{W}',
  '\\mathbb{X}',
  '\\mathbb{Y}',
  '\\mathbb{Z}',
  '\\mathbb{a}',
  '\\mathbb{b}',
  '\\mathbb{c}',
  '\\mathbb{d}',
  '\\mathbb{e}',
  '\\mathbb{f}',
  '\\mathbb{g}',
  '\\mathbb{h}',
  '\\mathbb{i}',
  '\\mathbb{j}',
  '\\mathbb{k}',
  '\\mathbb{l}',
  '\\mathbb{m}',
  '\\mathbb{n}',
  '\\mathbb{o}',
  '\\mathbb{p}',
  '\\mathbb{q}',
  '\\mathbb{r}',
  '\\mathbb{s}',
  '\\mathbb{t}',
  '\\mathbb{u}',
  '\\mathbb{v}',
  '\\mathbb{w}',
  '\\mathbb{x}',
  '\\mathbb{y}',
  '\\mathbb{z}',
];

export const geometry = [
  // '\\rightangle',
  '\\angle',
  '\\measuredangle', // '\\angmsd',
  '\\sphericalangle', // '\\angsph',
  // '\\angrtvb',
  // '\\righttriangle',
  // '\\epar',
  '\\bot',
  '\\nmid',
  '\\parallel',
  '\\nparallel',
  '\\colon',
  // '\\Colon',
  '\\therefore',
  '\\because',
  '\\blacksquare', // '\\qed',
];

export const commonMath = [
  /*
    fraction
  */
  '\\frac{x}{y}',
  // '\\sfrac{x}{y}',
  // '\\sfrac{x}{y}',
  '\\frac{x}{y}',
  '\\frac{dy}{dx}',
  '\\frac{\\Delta y}{\\Delta x}',
  '\\frac{\\partial y}{\\partial x}',
  '\\frac{\\delta y}{\\delta x}',
  '\\frac{\\pi}{2}',
  /*
    script
  */
  '{x}^{y}',
  '{x}_{i}',
  '{x}_{i}^{j}',
  '{_{i}^{j}}{x}',
  '{x}_{y^2}',
  'e^{-i\\omega t}',
  '{x}^{2}',
  '{_{1}^{n}}{Y}',
  /*
    radical
  */
  '\\sqrt{x}',
  '\\sqrt[n]{x}',
  '\\sqrt[2]{x}',
  '\\sqrt[3]{x}',
  '\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}',
  '\\sqrt{a^2+b^2}',
  /*
    integral
  */
  '\\int{}',
  '\\int_{a}^{b}{}',
  // '\\int_{a}^{b}{}',
  '\\iint{x}',
  '\\iint_{a}^{b}{}',
  // '\\iint_{a}^{b}{}',
  '\\iiint{}',
  '\\iiint_{a}^{b}{}',
  // '\\iiint_{a}^{b}{}',
  '\\oint{}',
  '\\oint_{a}^{b}{}',
  // '\\oint_{a}^{b}{}',
  // '\\oiint{}',
  // '\\oiint_{a}^{b}{}',
  // '\\oiint_{a}^{b}{}',
  // '\\oiiint{}',
  // '\\oiiint_{a}^{b}{}',
  // '\\oiiint_{a}^{b}{}',
  '\\,dx', // '\\box(24&dx)',
  '\\,dy', // '\\box(24&dy)',
  '\\,d\\theta', // '\\box(24&d\\theta)',
  /*
    large operator
  */
  '\\sum{}',
  '\\sum_{a}^{b}{}',
  // '\\sum_{a}^{b}{}',
  '\\sum_{a}{}',
  // '\\sum_{a}{}',
  '\\prod{}',
  '\\prod_{a}^{b}{}',
  // '\\prod_{a}^{b}{}',
  '\\prod_{a}{}',
  // '\\prod_{a}{}',
  '\\amalg{}',
  '\\amalg_{a}^{b}{}',
  // '\\amalg_{a}^{b}{}',
  '\\amalg_{a}{}',
  // '\\amalg_{a}{}',
  '\\bigcup{}',
  '\\bigcup_{a}^{b}{}',
  // '\\bigcup_{a}^{b}{}',
  '\\bigcup_{a}{}',
  // '\\bigcup_{a}{}',
  '\\bigcap{}',
  '\\bigcap_{a}^{b}{}',
  // '\\bigcap_{a}^{b}{}',
  '\\bigcap_{a}{}',
  // '\\bigcap_{a}{}',
  '\\bigvee{}',
  '\\bigvee_{a}^{b}{}',
  // '\\bigvee_{a}^{b}{}',
  '\\bigvee_{a}{}',
  // '\\bigvee_{a}{}',
  '\\bigwedge{}',
  '\\bigwedge_{a}^{b}{}',
  // '\\bigwedge_{a}^{b}{}',
  '\\bigwedge_{a}{}',
  // '\\bigwedge_{a}{}',
  '\\sum_{k}\\binom{n}{k}',
  '\\sum_{i=0}^{n}{}',
  // '\\0≤ i ≤ m0<j<n Pi,j',
  '\\prod_{k=1}^{n}A_k',
  '\\bigcup_{n=1}^{m}\\left(X_n\\cap Y_n\\right)',
  /*
    bracket
  */
  '\\left({}\\right)',
  '\\left[{}\\right]',
  '\\left\\{{}\\right\\}',
  // 'x',
  '\\left\\lfloor{}\\right\\rfloor',
  '\\left\\lceil{}\\right\\rceil',
  '\\left|{}\\right|',
  // 'x',
  '\\left[{}\\right[',
  '\\left]{}\\right]',
  '\\left]{}\\right[',
  // 'x',
  '\\left({}\\middle|{}\\right)',
  '\\left\\{{}\\middle|{}\\right\\}',
  '\\left\\langle{}\\middle|{}\\right\\rangle',
  '\\left\\langle{}\\middle|{}\\middle|{}\\right\\rangle',
  '\\left({}\\right.',
  '\\left.{}\\right)',
  '\\left[{}\\right.',
  '\\left.{}\\right]',
  '\\left\\{{}\\right.',
  '\\left.{}\\right\\}',
  '\\left\\langle{}\\right.',
  '\\left.{}\\right\\rangle',
  '\\left\\lfloor{}\\right.',
  '\\left.{}\\right\\rfloor',
  '\\left\\lceil{}\\right.',
  '\\left.{}\\right\\rceil',
  '\\left|{}\\right.',
  '\\left.{}\\right|',
  // 'a',
  // 'a',
  // 'a',
  // 'a',
  // 'xy',
  // 'xyz',
  '{{x}\\atop{y}}', // '\\{{x}\\atop{y}}',
  '\\binom{a}{b}',
  // '\\f\\left(x\\right)=-x,&x<0x,&x≥0',
  '\\binom{n}{k}',
  '\\left\\langle{{n}\\atop {k}}\\right\\rangle',
  /*
    function
  */
  '\\sin{}',
  '\\cos{}',
  '\\tan{}',
  '\\csc{}',
  '\\sec{}',
  '\\cot{}',
  '\\sin^{-1}{}',
  '\\cos^{-1}{}',
  '\\tan^{-1}{}',
  '\\csc^{-1}{}',
  '\\sec^{-1}{}',
  '\\cot^{-1}{}',
  '\\sinh{}',
  '\\cosh{}',
  '\\tanh{}',
  // '\\csch{}',
  // '\\sech{}',
  '\\coth{}',
  '\\sinh^{-1}{}',
  '\\cosh^{-1}{}',
  '\\tanh^{-1}{}',
  // '\\csch^{-1}{}',
  // '\\sech^{-1}{}',
  '\\coth^{-1}{}',
  '\\sin{\\theta}',
  '\\cos{2x}',
  '\\tan{\\theta}=\\frac{\\sin{\\theta}}{\\cos{\\theta}}',
  /*
    accent
  */
  '\\dot{a}',
  '\\ddot{a}',
  '\\dddot{a}',
  '\\hat{a}',
  '\\check{a}',
  '\\acute{a}',
  '\\grave{a}',
  '\\breve{a}',
  '\\widetilde{a}',
  '\\bar{a}',
  '\\bar{\\bar{a}}',
  // '\\overbrace{a}',
  // '\\underbrace{a}',
  // '\\buildrel{\\overbrace{b}}\\over{\\overbrace{a}}',
  // '\\{\\underbrace{a}}\\belowb',
  // 'a',
  '\\vec{a}',
  // 'a',
  // 'a',
  // '\\hvec{a}',
  '\\fbox{}',
  '\\fbox{$a^2=b^2+c^2$}',
  '\\overline{a}',
  '\\underline{a}',
  '\\overline{A}',
  '\\overline{ABC}',
  '\\overline{x\\oplus y}',
  /*
    limit and log
  */
  '\\log_{a}{b}',
  '\\log{a}',
  '\\lim_{}{}',
  '\\min_{}{}',
  '\\max_{}{}',
  '\\ln{}',
  '\\lim_{n\\rightarrow\\infty}{\\left(1+\\frac{1}{n}\\right)^n}',
  '\\max_{0\\le x\\le1}{xe^{-x^2}}',
  /*
    operator
  */
  '{\\colon=}',
  // '\\{==}',
  // '\\{+=}',
  // '\\{-=}',
  // '\\defeq',
  // '\\meq',
  // '\\Deltaeq',
  '{\\gets_{a}}',
  '\\rightarrow_{a}',
  // '\\buildrel{a}\\frac\\gets',
  // '\\buildrel{a}\\frac\\rightarrow',
  '\\Leftarrow_{a}',
  '\\Rightarrow_{a}',
  // '\\buildrel{a}\\frac\\Leftarrow',
  // '\\buildrel{a}\\frac\\Rightarrow',
  '\\leftrightarrow_{a}',
  // '\\buildrel{a}\\frac\\leftrightarrow',
  '\\Leftrightarrow_{a}',
  // '\\buildrel{a}\\frac\\Leftrightarrow',
  // '{\\buildrel y i e l d s\\frac\\rightarrow}',
  // '∆',
  /*
    matrix
  */
  '\\begin{matrix}{1}&{2}\\\\\\end{matrix}',
  '\\begin{matrix}{1}\\\\{2}\\\\\\end{matrix}',
  '\\begin{matrix}{1}&{2}&{3}\\\\\\end{matrix}',
  '\\begin{matrix}{1}\\\\{2}\\\\{3}\\\\\\end{matrix}',
  '\\begin{matrix}{1}&{2}\\\\{3}&{4}\\\\\\end{matrix}',
  '\\begin{matrix}{1}&{2}&{3}\\\\{4}&{5}&{6}\\\\\\end{matrix}',
  '\\begin{matrix}{1}&{2}\\\\{3}&{4}\\\\{5}&{6}\\\\\\end{matrix}',
  '\\begin{matrix}{1}&{2}&{3}\\\\{4}&{5}&{6}\\\\{7}&{8}&{9}\\\\\\end{matrix}',
  '\\cdots',
  '\\ldots',
  '\\vdots',
  '\\ddots',
  '\\begin{matrix}{1}&{0}\\\\{0}&{1}\\\\\\end{matrix}',
  '\\begin{matrix}{1}&{}\\\\{}&{1}\\\\\\end{matrix}',
  '\\begin{matrix}{1}&{0}&{0}\\\\{0}&{1}&{0}\\\\{0}&{0}&{1}\\\\\\end{matrix}',
  '\\begin{matrix}{1}&{}&{}\\\\{}&{1}&{}\\\\{}&{}&1\\\\\\end{matrix}',
  '\\left(\\begin{matrix}{1}&{2}\\\\{3}&{4}\\\\\\end{matrix}\\right)',
  '\\left[\\begin{matrix}{1}&{2}\\\\{3}&{4}\\\\\\end{matrix}\\right]',
  '\\left|\\begin{matrix}{1}&{2}\\\\{3}&{4}\\\\\\end{matrix}\\right|',
  // '1234',
  '\\left(\\begin{matrix}{1}&\\cdots&{2}\\\\\\vdots&\\ddots&\\vdots\\\\{3}&\\cdots&{4}\\\\\\end{matrix}\\right)',
  '\\left[\\begin{matrix}{1}&\\cdots&{2}\\\\\\vdots&\\ddots&\\vdots\\\\{3}&\\cdots&{4}\\\\\\end{matrix}\\right]',
];

MathjaxFactory().preload([
  ...basicMath,
  ...lowercase,
  ...uppercase,
  ...basicNaryOperators,
  ///...commonMath
]);